; =============================================================================
; HELLO.MNX — "Hello, world!" demo program for MNOS16
;
; This is the simplest possible user program.  It demonstrates:
;   - Relocatable v2 binary format (assembled at ORG 0, patched at load time)
;   - Using INT 0x80 SYS_PRINT_STRING to output text
;   - Clean return to shell via `ret`
;
; Loaded by the shell into the Transient Program Area (TPA) at USER_PROG_BASE.
; The shell applies v2 relocations, then calls the entry point from the header.
; Returns control to the shell by executing `ret`.
;
; Build:   Build-RelocModule (via build.ps1) or manually:
;          nasm -DRELOC_BASE=0 -f bin -I src/include/ -o hello.bin hello.asm
;          python tools/gen_relocs.py hello.asm --nasm tools/nasm/nasm.exe -o hello.rel
;          python tools/pack_module.py hello.bin hello.rel --magic MNEX --pad-sectors -o HELLO.MNX
;
; See doc/PROGRAM-LOADER.md for the full program loader specification.
; See doc/ABI.md for the binary portability contract.
; =============================================================================

%include "syscalls.inc"
%include "memory.inc"

%ifndef RELOC_BASE
%define RELOC_BASE 0
%endif

[BITS 16]
[ORG RELOC_BASE]

; =============================================================================
; No inline header — generated by pack_module.py toolchain (v2 format)
; =============================================================================

; =============================================================================
; ENTRY POINT
;
; The shell calls here via: call [run_entry_addr]
; (entry_offset in v2 header points to this label)
; =============================================================================
entry:
    ; Print greeting message
    mov si, msg_hello
    mov ah, SYS_PRINT_STRING
    int 0x80

    ; Return to shell (the `call` pushed a return address)
    ret

; =============================================================================
; DATA
; =============================================================================
msg_hello       db 'Hello, world!', 13, 10, 0
